### ISSUE TITLE
Error on running grunt server for the first time

### ISSUE THREAD

**Issue by shukran** [albogdano/bootup#1]
Hello and thanks for making this project!

I am new to assemble and following your instructions verbatim from https://www.npmjs.com/package/bootup

I can confirm I have all packages installed correctly, but upon running `grunt server` to kick off the project, I get the following error:

```
Running "assemble:htmls" (assemble) task
Warning: Cannot read property 'stage' of undefined Use --force to continue.

Aborted due to warnings.
```

I haven't added any of my own pages yet, but I sort of assumed the example sites would build and the server would launch.

Any and all help would be greatly appreciated! 

Thank you.

**Comment by albogdano** [comment]
Hi, thanks for reporting this. I tried reproducing this on my machine but didn't get any errors. Can you tell me if you're downloading bootUp from `npm install` or you download/clone the whole repository. This error is about assemble - a missing config maybe, not sure. Try running `grunt -v` for more info about the error.

I'm running node 5.3.0 and npm 3.3.12, grunt-cli 0.1.13 and grunt 0.4.5.

**Comment by albogdano** [comment]
I'm running node 5.3.0 and npm 3.3.12.

**Comment by albogdano** [comment]
You should get the latest Node.js and download the updated repository again. I locked the dependencies so they don't break `grunt server` after `npm install` or `npm update`.

**Comment by shukran** [comment]
Thanks for the quick followup! Sorry I was at family Christmas stuff so only got to this now. I'll try that, and I assume that's what it is. I am stuck on an old version of node at work (v 0) and that's probably what threw it off. Thanks!!

**Comment by albogdano** [comment]
Please let me know if your're still having problems after this. The problem comes from the fact that Node modules are unstable especially after the transition from 0.10.x to 4.0.0 and 5.0.0. I originally made this with 0.10.x and it all worked fine, then Assemble made some breaking changes and other modules also got updated and now my guess is that a thousand other modules are broken as well because of that. It's one big mess right now.
